[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/hlc23"
weight = 1

    [social.params]
    icon = "brand-github"


[[social]]
identifier = "email"
name = "Email"
url = "mailto:henryleecode23@gmail.com"
weight = 2

    [social.params]
    icon = "email"
