baseURL = 'https://hlc23.github.io'
languageCode = 'zh-tw'
title = "hlc23's blog"
theme = "hugo-theme-stack"

[params.sidebar.avatar]
src = "img/avatar.jpg"

[menu]
    [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/hlc23"
    weight = 1

        [menu.social.params]
        icon = "brand-github"


    [[menu.social]]
    identifier = "email"
    name = "Email"
    url = "mailto:henryleecode23@gmail.com"
    weight = 2

        [menu.social.params]
        icon = "email"
